[package]
name = "validator_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"

# Lien vers l'application principale (votre lib interne)
raise = { path = "../../" }
